---

- name: Ensure iptables see bridged traffic
  sysctl:
    name: net.bridge.bridge-nf-call-ip6tables
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf

- name: Ensure iptables see bridged traffic
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_file: /etc/sysctl.d/k8s.conf


- name: Kubernetes Repo
  yum_repository:
    name: Kubernetes
    description: Kubernetes
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: 
      - "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
      - "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"

- name: Install kube tools
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present

- name: Ensure kubelet is enabled
  systemd:
    name: kubelet
    state: started
    enabled: yes



