---

- name: Install prerequirements
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: latest

- name: Add Docker repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/
    mode: '0644'

- name: Install Docker Engine
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: yes
    state: latest

- name: Setup Docker daemon
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json

- name: Start Docker
  systemd:
    name: docker
    state: started
    enabled: yes



